import { ToastContainer } from "react-toastify";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, modal }) {

  return (
    <html lang="en">
      <body>
            <ToastContainer />
            {children}
            {/* {modal} */}
      </body>
    </html>
  );
}
